# Generated by Django 5.0.7 on 2024-08-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='number_of_travelers',
            field=models.PositiveIntegerField(),
        ),
    ]
